server:
  port: 8100

spring:
  application:
    name: customer
  datasource:
    username: calebpitan
    url: jdbc:postgresql://localhost:5432/customer
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true